In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("C:/Users/wjdtj/OneDrive - dgu.ac.kr/데이터 분석/교통사고/교통사고 데이터 셋/교통사고 구급출동 현황_2011_2020.csv")
df.head()

C:\Users\wjdtj\AppData\Local\Temp\ipykernel_12824\3921947699.py:1: DtypeWarning: Columns (9,84,85,93) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv("C:/Users/wjdtj/OneDrive - dgu.ac.kr/데이터 분석/교통사고/교통사고 데이터 셋/교통사고 구급출동 현황_2011_2020.csv")

,relif_reprt_no,reg_cmptn_se_nm,patnt_ocrn_type_se_nm,trnsport_acdnt_nm,trnsport_acdnt_etc_nm,frstt_nm,ward_nm,lfdau_nm,relif_act_se_nm,hlcptr_pmblnc_ennc_nm,...,spt_dist2,retrns_resn2,trans_cl_nm,trans_cl_resn,time_unit_tmprt,time_unit_rainqty,time_unit_ws,time_unit_wd,time_unit_humidity,time_unit_msnf
0,20114504107M00001,등록완료,질병외,운전자,NaN,익산소방서,함열119안전센터,NaN,NaN,NaN,...,NaN,NaN,미이송,[타차]택시,-9.0,NaN,0.9,160.0,86.0,5.8
1,20114504103M00001,등록완료,질병외,보행자,NaN,익산소방서,남중119안전센터,NaN,특수일반,NaN,...,NaN,NaN,이송,NaN,-10.0,NaN,0.7,160.0,79.0,5.8
2,20114504306M00001,등록완료,질병외,운전자,NaN,익산소방서,함열119안전센터,용동119지역대,NaN,NaN,...,NaN,NaN,이송,NaN,-3.5,NaN,1.4,290.0,55.0,5.4
3,20114502105M00003,등록완료,질병외,운전자,NaN,전주완산소방서,임실119안전센터,NaN,특수일반,NaN,...,NaN,NaN,이송,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20114510104M00001,등록완료,질병외,동승자,NaN,무진장소방서,진안119안전센터,NaN,특수일반,NaN,...,NaN,NaN,이송,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 변수명 통일

In [4]:
df2=pd.read_csv("C:/Users/wjdtj/OneDrive - dgu.ac.kr/데이터 분석/교통사고/교통사고 데이터 셋/구급출동_전주_2020_2022_최종.csv",encoding='cp949')

In [5]:
df.head()

,relif_reprt_no,reg_cmptn_se_nm,patnt_ocrn_type_se_nm,trnsport_acdnt_nm,trnsport_acdnt_etc_nm,frstt_nm,ward_nm,lfdau_nm,relif_act_se_nm,hlcptr_pmblnc_ennc_nm,...,spt_dist2,retrns_resn2,trans_cl_nm,trans_cl_resn,time_unit_tmprt,time_unit_rainqty,time_unit_ws,time_unit_wd,time_unit_humidity,time_unit_msnf
0,20114504107M00001,등록완료,질병외,운전자,NaN,익산소방서,함열119안전센터,NaN,NaN,NaN,...,NaN,NaN,미이송,[타차]택시,-9.0,NaN,0.9,160.0,86.0,5.8
1,20114504103M00001,등록완료,질병외,보행자,NaN,익산소방서,남중119안전센터,NaN,특수일반,NaN,...,NaN,NaN,이송,NaN,-10.0,NaN,0.7,160.0,79.0,5.8
2,20114504306M00001,등록완료,질병외,운전자,NaN,익산소방서,함열119안전센터,용동119지역대,NaN,NaN,...,NaN,NaN,이송,NaN,-3.5,NaN,1.4,290.0,55.0,5.4
3,20114502105M00003,등록완료,질병외,운전자,NaN,전주완산소방서,임실119안전센터,NaN,특수일반,NaN,...,NaN,NaN,이송,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,20114510104M00001,등록완료,질병외,동승자,NaN,무진장소방서,진안119안전센터,NaN,특수일반,NaN,...,NaN,NaN,이송,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.columns=(df2.columns)
df.columns

Index(['구급보고서번호', '등록완료구분명', '환자발생유형구분명', '교통사고명', '교통사고기타명', '소방서명', '서센터명',
       '소방지역대명', '구급활동구분명', '헬리콥터펌뷸런스유무명',
       ...
       '현장거리2', '재이송사유2', '이송분류명', '이송분류사유', '시간단위기온', '시간단위강수량', '시간단위풍속',
       '시간단위풍향', '시간단위습도', '시간단위적설량'],
      dtype='object', length=102)

# 전주시 자료만 & 연도(3개년)별로 분리

In [7]:
df = df[(df['시군구명'].str.startswith('전주시', na=False))]

In [8]:
df_17_19=df[(df['신고연도']>=2017) & (df['신고연도']<=2019)]

In [9]:
df_17_19['신고연도'].value_counts()

신고연도
2017    2849
2019    2812
2018    2718
Name: count, dtype: int64

In [10]:
df_14_16=df[(df['신고연도']>=2014) & (df['신고연도']<=2016)]
df_14_16['신고연도'].value_counts()

신고연도
2016    2798
2015    2726
2014    2468
Name: count, dtype: int64

In [12]:
# df_14_16.to_csv("C:/Users/wjdtj/OneDrive - dgu.ac.kr/데이터 분석/교통사고/0525/df_14_16.csv",encoding='cp949',index=False)
# df_17_19.to_csv("C:/Users/wjdtj/OneDrive - dgu.ac.kr/데이터 분석/교통사고/0525/df_17_19.csv",encoding='cp949',index=False)

# 학교

In [13]:
school=pd.read_csv("C:/Users/wjdtj/OneDrive - dgu.ac.kr/데이터 분석/교통사고/0525/전국초중등학교위치표준데이터.csv",encoding='cp949')
school.columns

Index(['학교ID', '학교명', '학교급구분', '설립일자', '설립형태', '본교분교구분', '운영상태', '소재지지번주소',
       '소재지도로명주소', '시도교육청코드', '시도교육청명', '교육지원청코드', '교육지원청명', '생성일자', '변경일자',
       '위도', '경도', '데이터기준일자', '제공기관코드', '제공기관명'],
      dtype='object')

In [14]:
school.head()

,학교ID,학교명,학교급구분,설립일자,설립형태,본교분교구분,운영상태,소재지지번주소,소재지도로명주소,시도교육청코드,시도교육청명,교육지원청코드,교육지원청명,생성일자,변경일자,위도,경도,데이터기준일자,제공기관코드,제공기관명
0,B000004806,미원초등학교장락분교장,초등학교,1944-04-06,공립,분교,운영,경기도 가평군 설악면 미사리 290-3,경기도 가평군 설악면 미사리로 588,7530000,경기도교육청,7721000,경기도가평교육지원청,2013-11-29,2023-11-15,37.703889,127.540156,2024-03-22,C738100,청주대학교 지방교육재정연구원
1,B000005055,모곡초등학교,초등학교,1934-12-15,공립,본교,운영,강원특별자치도 홍천군 서면 모곡리 184-2,강원특별자치도 홍천군 서면 설밀길 76,7801000,강원특별자치도교육청,7882000,강원특별자치도홍천교육지원청,2013-11-29,2023-11-15,37.676874,127.600664,2024-03-22,C738100,청주대학교 지방교육재정연구원
2,B000007420,울진남부초등학교,초등학교,1968-10-22,공립,본교,운영,경상북도 울진군 울진읍 읍내리 290,경상북도 울진군 울진읍 울진중앙로 52-5,8750000,경상북도교육청,8971000,경상북도울진교육지원청,2013-11-29,2023-11-15,36.987340,129.399471,2024-03-22,C738100,청주대학교 지방교육재정연구원
3,B000022879,목포부주초등학교,초등학교,2016-03-01,공립,본교,운영,전라남도 목포시 옥암동 1317,전라남도 목포시 남악2로22번길 37,8490000,전라남도교육청,8501000,전라남도목포교육지원청,2013-11-29,2023-11-15,34.808753,126.456974,2024-03-22,C738100,청주대학교 지방교육재정연구원
4,B000006241,용동초등학교,초등학교,1950-04-20,공립,본교,운영,전북특별자치도 김제시 용지면 장신리 280,전북특별자치도 김제시 용지면 용덕길 36,8321000,전북특별자치도교육청,8382000,전북특별자치도김제교육지원청,2013-11-29,2023-11-15,35.854580,127.003365,2024-03-22,C738100,청주대학교 지방교육재정연구원

In [15]:
# '설립일자' 열을 datetime 타입으로 변환
school['설립일자'] = pd.to_datetime(school['설립일자'])

In [17]:
# 2017년 1월 1일 이전에 설립된 학교만 필터링
school_14_16 = school[school['설립일자'] <= pd.Timestamp('2017-01-01')]
school_14_16 = school_14_16[(school_14_16['소재지지번주소'].str.startswith('전북특별자치도 전주시', na=False))]

In [18]:
# 2020년 1월 1일 이전에 설립된 학교만 필터링
school_17_19 = school[school['설립일자'] <= pd.Timestamp('2020-01-01')]
school_17_19 = school_17_19[(school_17_19['소재지지번주소'].str.startswith('전북특별자치도 전주시', na=False))]

In [20]:
# school_14_16.to_csv("C:/Users/wjdtj/OneDrive - dgu.ac.kr/데이터 분석/교통사고/0525/school_14_16.csv",encoding='cp949',index=False)
# school_17_19.to_csv("C:/Users/wjdtj/OneDrive - dgu.ac.kr/데이터 분석/교통사고/0525/school_17_19.csv",encoding='cp949',index=False)

# 횡단보도

# 교차로

# 버스 정류소